CC=gcc-7
CFLAGS=-I.


history_based_activator: 
	gcc -O0 history_based_activator.c ../../include/*.o -o history_based_activator -lpthread -static

all: history_based_activator
v1: history_based_activator

clean:
	rm history_based_activator
